### PR TITLE
HSTS support

### PR DESCRIPTION
**Pull request by lcacciagioni**
Please don't merge yet, since I need to sign and send the CLA to the foundation. Anyway @geofffranks can you please tell me how it looks?

Issue #49 

Thanks,
Leandro.-

PS: I haven't enabled it for WSS because the [IETF Spec](https://tools.ietf.org/html/rfc6797) establish this only for HTTP.

### CODE REVIEW

**Comment by lcacciagioni** [comment]
Today I have submitted the CLA to the organization did I need to wait for any kind of approval from them?

**Comment by geofffranks** [comment]
Looks like they may not have processed the CLA yet, since according to the bot, i just needed to close/reopen this.. but, the content looks good

**Comment by chipchilders** [comment]
close / reopen to update CLA status

**Comment by chipchilders** [comment]
close / reopen to update CLA status

**Pull request merged**
