### PR TITLE
Enable ha proxy to have bind ip

### PR DESCRIPTION
**Pull request by datianshi**
I would like to build VM with multiple ethernet. But did not find option to bind a specified IP. So provided this property

### CODE REVIEW

**Comment by geofffranks** [comment]
@datianshi can you add the bind IP support to the 4443 frontend + the frontends for the tcp mode?

**Comment by shinji62** [comment]
Agree with @geofffranks `all or nothing` :)

**Comment by datianshi** [comment]
@geofffranks  Added the binding IP to 4443. Also squashed with previous commit.
Thanks

**Comment by geofffranks** [comment]
@datianshi how about the `bind` directive for `tcp-frontend-*`?

**Comment by datianshi** [comment]
sorry missed the tcp mode... already changed the commit and squashed @geofffranks

**Comment by geofffranks** [comment]
👍 thanks!

**Pull request merged**
